dist: trusty
sudo: false
language: java
env:
   global:
    - MAVEN_OPTS="-Dformatter.skip=true -Dsurefire.useFile=false -Dmaven.artifact.threads=64 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
before_cache:
  - rm -Rf $HOME/.m2/repository/org/apache/winegrower
cache:
  timeout: 1000
  directories:
  - "$HOME/.m2"

install: echo true

jobs:
  include:
    # PR profile
    - stage: pullrequest_build
      script: mvn clean install
      jdk: oraclejdk8

    # master profile
    - stage: master_build
      env:
      - STEP=Build Oracle 8 JVM
      script: mvn clean install
      jdk: oraclejdk8

    - stage: master_build
      env:
      - STEP=Build OpenJDK 8 JVM
      script: mvn clean install
      jdk: openjdk8

    - stage: master_build
      env:
      - STEP=Build OpenJDK 11 JVM
      script: mvn clean install
      jdk: openjdk11

    - stage: master_build
      env:
      - STEP=Update Documentation
      script: cd winegrower-documentation && mvn pre-site -Pgh-pages --settings ../.travis/settings.xml
      jdk: oraclejdk8

    - stage: master_build
      env:
      - STEP=Sonatype Audit
      script: travis_wait 50 mvn install -DskipTests ossindex:audit
      jdk: oraclejdk8

stages:
  - name: master_build
    if: branch = master AND type != pull_request
  - name: pullrequest_build
    if: type = pull_request

